### ISSUE TITLE
Decentralized gaming vs blockchain gaming

### ISSUE THREAD

**Issue by KillariDev** [DecentralisedGaming/Book#14]
"The goal of this book is to be a useful source of information on blockchain game technology. " .

I think we could try to discuss about other kind of decentralized gaming too, not necessary only blockchain. Eg. TOR and torrents are good decentralized systems too. I am not aware of any decentralized games not using blockchain tech thought. But I think that could be an interesting topic that could be explored.

**Comment by DecentralisedGaming** [comment]
Good point! We'd need some research into this topic as I'm not so knowledgeable myself!

They can definitely be a part of the book, especially for stateless / one-shot games as you suggested in private.

**Comment by DecentralisedGaming** [comment]
This was fixed in #18
